### ISSUE TITLE
bug: Lightpush's publish type error

### ISSUE THREAD

**Issue by AlejandroCabeza** [waku-org/nwaku#2253] opened 2023-11-28 10:31 UTC
### Problem
`WakuLightPushClient.publish` fails with "dial failure" when `peer` is `PeerId`.

### Impact
...

### To reproduce
1. Instantiate two `Switch`, one will act as `serverSwitch` and the other as `clientSwitch`.
2. Instantiate a `WakuLightPush` and a `WakuLightPushClient`, using the respective switches.
3. Send a `publish` request using `serverSwitch.peerInfo.toRemotePeerInfo().peerId`.
4. The response will be a "dial failure".

In step 3, if using `serverSwitch.peerInfo.toRemotePeerInfo()`, it will be successful.

### Expected behavior
The method works fine when sending a `RemotePeerId` instead of `PeerId`. That is weird given `RemotePeerId` contains  `PeerId`, hence I expected the method to behave exactly the same.

### nwaku version/commit hash
- Wakunode: v0.22.0-rc.0-26-g3dcfbf
- Git: 4cbc6490f39aa710b1670976e651f6d26a4c4a32 | [branch](https://github.com/waku-org/nwaku/tree/light-push)
- PR: https://github.com/waku-org/nwaku/pull/2252

**Comment by gabrielmer** [comment] 2024-06-10 11:48
> It's been a bit so I can't anything extra aside from what I posted. You weren't able to reproduce it?

I was looking for the specific piece of code where it is supposed to reproduce instead of writing it, which is very error prone. No worries then :))

In future cases I think it would be better to provide the code so we all run the same thing and are on the same page.

**Comment by AlejandroCabeza** [comment] 2024-06-10 14:34
> > It's been a bit so I can't anything extra aside from what I posted. You weren't able to reproduce it?
> 
> I was looking for the specific piece of code where it is supposed to reproduce instead of writing it, which is very error prone. No worries then :))
> 
> In future cases I think it would be better to provide the code so we all run the same thing and are on the same page.

Generally I tend to leave a test for these cases, I don't know why I didn't on this occasion 🤔

**Comment by gabrielmer** [comment] 2024-06-27 16:05
I was able to reproduce it :)

I wrote the following test in https://github.com/waku-org/nwaku/blob/76d5b2642d4467af439552f3a1072c4e4abff232/tests/waku_lightpush/test_client.nim

```
asyncTest "Test publish with peerId":
      let publishResponse =
        await client.publish(pubsubTopic, message, serverRemotePeerInfo.peerId)
      assertResultOk publishResponse
```

and I get the dial failure. If I use `serverRemotePeerInfo` instead of its peerId, test passes.

This is expected, as we can't dial a peer only knowing its `peerId`, we need to know its full multiaddress.

It's true that we can try to dial it only using the `peerId` by calling the following proc https://github.com/waku-org/nwaku/blob/76d5b2642d4467af439552f3a1072c4e4abff232/waku/node/peer_manager/peer_manager.nim#L627-L638

But it will only work if the multiaddress of that `peerId` is saved in the `peerStore`. If the complete information is not stored, then we can't dial by only using the `peerId`

So it seems to be expected then. Closing the issue :) please reopen in case anything is missing or not ok

**Closed by gabrielmer** 2024-06-27 16:05 UTC
Labels: bug, effort/hours
