### ISSUE TITLE
bug: relay push with malformed timestamp crashes nwaku

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/nwaku#2198] opened 2023-11-08 14:24 UTC
### Problem
Sending this curl on wakuorg/nwaku:latest crashes the node:
`curl -vv -X POST "http://localhost:17083/relay/v1/messages/%2Fwaku%2F2%2Fdefault-waku%2Fproto" -H "accept: text/plain" -H "content-type: application/json" -d '{"payload": "SGVsbG8gV29ybGQh", "contentTopic": "/test/1/waku-relay/proto", "timestamp": 9223372036854775808}'`

Stack Trace:
```
/app/apps/wakunode2/wakunode2.nim(144) wakunode2
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(1179) runForever
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(146) poll
/app/vendor/nim-chronos/chronos/internal/asyncfutures.nim(359) futureContinue
/app/vendor/nim-presto/presto/serverprivate.nim(197) processRestRequest
/app/vendor/nim-presto/presto/route.nim(387) restRelayV1MessagesPubsubTopicPostHandler
/app/vendor/nim-chronos/chronos/internal/asyncfutures.nim(359) futureContinue
/app/waku/waku_api/rest/relay/handlers.nim(147) restRelayV1MessagesPubsubTopicPostHandler
/app/vendor/nim-serialization/serialization.nim(51) decodeFromJsonBytes
/app/waku/waku_api/rest/relay/types.nim(97) readValue
/app/vendor/nim-serialization/serialization.nim(31) readValue
/app/vendor/nim-json-serialization/json_serialization/reader.nim(600) readValue
/app/vendor/nimbus-build-system/vendor/Nim/lib/system/chcks.nim(61) raiseRangeErrorNoArgs
/app/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(54) sysFatal
[[reraised from:
/app/apps/wakunode2/wakunode2.nim(144) wakunode2
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(1179) runForever
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(146) poll
/app/vendor/nim-chronos/chronos/internal/asyncfutures.nim(359) futureContinue
/app/vendor/nim-presto/presto/serverprivate.nim(197) processRestRequest
/app/vendor/nim-presto/presto/route.nim(387) restRelayV1MessagesPubsubTopicPostHandler
/app/vendor/nim-chronos/chronos/internal/asyncfutures.nim(359) futureContinue
/app/waku/waku_api/rest/relay/handlers.nim(182) restRelayV1MessagesPubsubTopicPostHandler
]]
[[reraised from:
/app/apps/wakunode2/wakunode2.nim(144) wakunode2
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(1179) runForever
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(146) poll
/app/vendor/nim-chronos/chronos/internal/asyncfutures.nim(359) futureContinue
/app/vendor/nim-chronos/chronos/internal/asyncmacro.nim(411) processRestRequest
]]
[[reraised from:
/app/apps/wakunode2/wakunode2.nim(144) wakunode2
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(1179) runForever
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(146) poll
/app/vendor/nim-chronos/chronos/internal/asyncfutures.nim(359) futureContinue
/app/vendor/nim-presto/presto/serverprivate.nim(383) processRestRequest
]]
[[reraised from:
/app/apps/wakunode2/wakunode2.nim(144) wakunode2
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(1179) runForever
/app/vendor/nim-chronos/chronos/internal/asyncengine.nim(146) poll
/app/vendor/nim-chronos/chronos/internal/asyncfutures.nim(359) futureContinue
/app/vendor/nim-presto/presto/serverprivate.nim(383) processRestRequest
]]
Error: unhandled exception: value out of range [RangeDefect]
```

**Comment by NagyZoltanPeter** [comment] 2023-11-15 05:19
Had a quick check and found the issue is within nim json serialization library.
The implemented range check does not hit for some specific value - in this case it is '9223372036854775808' which is effectively -0 causing numeric error which is not a catchable exception in this case.
This issue that the tokenizer gets type of unsigned int type identified while we do expect signed thus the corner case check does not hit.
https://github.com/waku-org/nwaku/blob/85b7ea093cb85ee4f433a617b97571bd709d30df/json_serialization/reader.nim#L600-L601

@chair28980 : Need fix in json_serialization library!

**Comment by gabrielmer** [comment] 2023-11-24 17:26
**Weekly Update**

- _achieved_: analyzed issue, found and implemented fix, raised PR in `nim-json-serialization` repo and implemented feedback. Merged fix and opened a PR in nwaku updating the dependency.
- _next_: get nwaku PR reviewed y merge

**Closed** 2023-11-28 10:47 UTC
Labels: bug
