### ISSUE TITLE
Support distributed message tracing

### ISSUE THREAD

**Issue by oskarth** [waku-org/nwaku#747] opened 2021-10-15 04:45 UTC
# Problem

As a developer, I want to be able to see messages across logs of multiple nodes that I can inspect.

(This assumes it is a controlled test cluster / opt-in for things like community dogfooding debugging).

## Suggested solution

We can easily add, say, MD5 hash of WakuMessage upon publish here: https://github.com/status-im/nim-waku/blob/master/waku/v2/node/wakunode2.nim#L305

It isn't obvious to me how to best instrument hashes of WakuMessage in relaying/gossiping, but should be doable with some optional instrumentation.

Similar thing can be done for store.

### Future improvements

Based on this, later on this can be extended as a context function with additional actions, such as integrating Kibana with https://opentracing.io/ etc.

For now, just being able to search for a message hash and see it across nodes seems useful.

cc @jm-clius fyi and for ideas
cc @jakubgs in case you know of this being done somewhere
cc @dryajov if this is done/been though about at a libp2p level (I know it has been talked about in libp2p world but unclear if it has been actioned on)

**Comment by jm-clius** [comment] 2023-01-06 14:54
Closing as duplicate of https://github.com/waku-org/nwaku/issues/1394

**Closed by jm-clius** 2023-01-06 14:54 UTC
