### ISSUE TITLE
chore: do not advertise multiaddr with port 0

### ISSUE THREAD

**Issue by vpavlin** [waku-org/nwaku#1883] opened 2023-08-03 16:10 UTC
### Background

When you explicitly set the `--tcp-port=0`, the resulting MA used by the waku node will contain the port 0:

```
$ ./build/wakunode2 --relay --tcp-port=0
INF 2023-08-03 18:03:15.264+02:00 Initializing networking                    tid=234166 file=waku_node.nim:142 addrs=@[/ip4/10.1.6.152/tcp/0]
INF 2023-08-03 18:03:15.264+02:00 mounting relay protocol                    topics="waku node" tid=234166 file=waku_node.nim:309
INF 2023-08-03 18:03:15.264+02:00 relay mounted successfully                 topics="waku node" tid=234166 file=waku_node.nim:328
INF 2023-08-03 18:03:15.264+02:00 mounting rendezvous discovery protocol     topics="waku node" tid=234166 file=waku_node.nim:778
INF 2023-08-03 18:03:15.264+02:00 mounting libp2p ping protocol              topics="waku node" tid=234166 file=waku_node.nim:736
INF 2023-08-03 18:03:15.264+02:00 mounting store client                      topics="waku node" tid=234166 file=waku_node.nim:543
INF 2023-08-03 18:03:15.264+02:00 Starting Waku node                         topics="waku node" tid=234166 file=waku_node.nim:793 version=v0.19.0-rc.0-5-gd2b607
INF 2023-08-03 18:03:15.264+02:00 PeerInfo                                   topics="waku node" tid=234166 file=waku_node.nim:796 peerId=16U*2SdE95 addrs=@[]
INF 2023-08-03 18:03:15.264+02:00 Listening on                               topics="waku node" tid=234166 file=waku_node.nim:803 full=[/ip4/10.1.6.152/tcp/0/p2p/16Uiu2HAkzF2Q9v7EUJQyiqGbV2GhrkKKGSp5Do3ZtiWpR92SdE95]
```

which is obviously not true. Waku should advertise the real port  it is listening on in the multiaddress

### Acceptance criteria

- [ ] waku advertises the real port it is listening on instead of port 0 when instructed to use a random port

**Comment by gabrielmer** [comment] 2023-09-11 07:12
**Weekly Update**

- _next_: analyze and fix issue

**Comment by gabrielmer** [comment] 2023-09-15 14:06
**Weekly Update**

- _achieved_: tested two different solutions: updating the port with an addressMapper, and not allowing the user to use port 0. Analyzed and discussed technical implications of both solutions. Initially followed decision to proceed with 2nd solution for now, with intention of implementing the first solution in the future. 
Opened a draft PR and updated tests for the solution of not allowing the user to choose port 0.
- _next_: after further feedback received today, we have to complete the discussion of how to move forward and either review and proceed with current PR, or plan and implement solution that updates all the data structures consistently across the nodes

**Comment by mfw78** [comment] 2023-09-16 07:21
Sorry for the nit, can this issue use "multiaddr" as opposed to "MA" due search ambiguity?

**Comment by gabrielmer** [comment] 2023-09-19 07:18
> Sorry for the nit, can this issue use "multiaddr" as opposed to "MA" due to search ambiguity?

No problem! Done :)

**Comment by gabrielmer** [comment] 2023-09-26 11:58
Closing as duplicate of #2042

**Closed by gabrielmer** 2023-09-26 11:58 UTC
Labels: bug, good first issue
