### ISSUE TITLE
wakucanary: certificate required for wss?

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#1732] opened 2023-05-15 15:25 UTC
I setup a wakunode that uses a domain name + certificate + wss
I tried setting up wakucanary to check its status and ended up with the following error:
```
richard@laptop:~/waku-org/nwaku$ ./build/wakucanary -a=/dns4/my.domain.com/tcp/443/wss/p2p/16Uiu2HAmMGhfSTUzKbsjMWxc6T1X4wiTWSF1bEWSLjAukCm7KiHV
INF 2023-05-15 11:08:37.268-04:00 Cli flags                                  tid=495811 file=wakucanary.nim:119 address=/dns4/my.domain.com/tcp/443/wss/p2p/16Uiu2HAmMGhfSTUzKbsjMWxc6T1X4wiTWSF1bEWSLjAukCm7KiHV timeout=10s protocols=@[] logLevel=DEBUG
ERR 2023-05-15 11:08:37.269-04:00 WebSocket Secure requires key and certificate, see --help tid=495811 file=wakucanary.nim:153
ERR 2023-05-15 11:08:37.269-04:00 The node has some problems (see logs)      tid=495811 file=wakucanary.nim:191
```

Is it really necessary as a client app to have a certificate in order to be able to connect to a node that uses wss?

**Comment by vpavlin** [comment] 2023-05-15 15:28
Thanks, yeah, now that I think about it, it might not be necessary to setup wakucanary with WSS endpoint as it's only purpose is to connect to existing WSS and not expose one.

I'll take a better look at this in next few days to see if my original wakucanary change was a bit too enthusiastic:)

**Comment by vpavlin** [comment] 2023-05-24 11:53
I looked into it briefly today and tried to remove the certificate requirement, but then wakucanary was not able to connect to any WSS enabled node.

It might just be a "misconfiguration" somewhere deeper in the code which we could resolve, but I am not sure.

@jm-clius any insight here?

**Comment by chair28980** [comment] 2024-01-04 15:01
@vpavlin is this issue still relevant? Should it be picked up by nwaku team or is ok to close?

**Comment by chair28980** [comment] 2024-02-20 15:19
Closing as duplicate of https://github.com/waku-org/nwaku/issues/2349

**Closed by chair28980** 2024-02-20 15:19 UTC
Labels: bug
