### ISSUE TITLE
feat: Have additional Admin REST API endpoints that helps node operator in monitoring

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/nwaku#2290] opened 2023-12-14 06:08 UTC
### Problem
While debugging [issue](https://github.com/status-im/status-go/issues/4459) faced in status app, realized that it would be helpful to have some admin REST API's or some form for node operators to inspect their node in case of issues. This would also inturn help Waku team analyze an issue further(e.g in the waku network as well). 

### Suggested solution
Have a set of Admin API's for service protocols that help in inspecting some data-structures used by various protocols in a service node. 
-  For filter protocol, it would be good if we can query the list of current subscriptions that are currently active at the node. The response can include details like contentTopics and/or pubsubTopics subscribed to, peer details,  and probably current state of connection to the peer. 
- Similar analysis can be done for other service protocols as well and have such API's that can help introspect into the node further.

Note: Also observed that we are not logging contentTopics when a filter subscription is created in the logs, it would help to log it as well. https://github.com/waku-org/nwaku/blob/0cc0c80563339c9466c5e3711735a331fbc8ac2c/waku/waku_filter_v2/protocol.nim#L115

### Alternatives considered
None

### Additional context
None

### Acceptance criteria

- [ ] A Admin query REST API to query list of active filter subscriptions.

### QA Test Scenario Description
Scenario 1
1. 
2. 
Scenario 2
1. 
2.

**Comment by jm-clius** [comment] 2023-12-14 07:05
> Note: Also observed that we are not logging contentTopics when a filter subscription is created in the logs, it would help to log it as well.

Interesting, because just based on the line you quoted, it seems like we log the entire request (i.e. it should be visible in the `kv_raw` part of the logged JSON object). Are we sure the logged requests contain content topics?

**Comment by chaitanyaprem** [comment] 2023-12-14 07:19
> > Note: Also observed that we are not logging contentTopics when a filter subscription is created in the logs, it would help to log it as well.
> 
> Interesting, because just based on the line you quoted, it seems like we log the entire request (i.e. it should be visible in the `kv_raw` part of the logged JSON object). Are we sure the logged requests contain content topics?

Logs in fleet generated when i start my desktop instance not having contentTopics

![image](https://github.com/waku-org/nwaku/assets/20137744/deb2affc-1333-4b53-aadd-cd3cdc48c169)

When i tested locally by running an nwaku node and sending a filter subscribe request, noticed that logs don't have contentTopics. Which probably means it is getting skipped from logging.

![image](https://github.com/waku-org/nwaku/assets/20137744/7dd0ad48-0613-4e7c-a23c-ccab9d44c482)

**Comment by jm-clius** [comment] 2023-12-14 07:39
Thanks! Seems to indicate that the full object is not stringified and can likely easily be rectified by a proper `$` implementation.

**Comment by gabrielmer** [comment] 2023-12-14 13:04
> Thanks! Seems to indicate that the full object is not stringified and can likely easily be rectified by a proper `$` implementation.

Exactly! Just opened a [PR](https://github.com/waku-org/nwaku/pull/2295) for the logging issue by improving the `$` implementation

**Comment by gabrielmer** [comment] 2023-12-15 17:58
**Weekly Update**

- _achieved_: improved logging and merged. Created locally a new REST endpoint that returns the information of all the filter subscriptions on a service node
- _next_: add unit tests, update documentation and open PR

**Comment by gabrielmer** [comment] 2023-12-22 16:50
**Weekly Update**

- _achieved_: improved initial implementation. Added unit tests, updated documentation, opened and got approved PR.
- _next_: verify if there's other places where the new endpoint should be document before merging

**Comment by gabrielmer** [comment] 2024-01-05 16:41
**Weekly Update**

- _achieved_: got feedback about improved error handling. Added it to the code, got a segfault from the testing framework, investigated and found the root cause.
- _next_: define how to proceed based on the testing issue and merge the PR

**Closed** 2024-01-09 10:42 UTC
Labels: enhancement, critical, status-waku-integ

**Comment by gabrielmer** [comment] 2024-01-09 10:45
@chaitanyaprem filter admin endpoint is merged :)

Please let me know if there's any other admin endpoint for other protocols that might be useful and I can open separate issues for each requested endpoint
