### ISSUE TITLE
bug: networkReachability=NotReachable log?

### ISSUE THREAD

**Issue by dao** [waku-org/nwaku#1499] opened 2023-01-17 18:00 UTC
### Problem
Running status-im/nwaku:0.14.0 docker image, I observe previously unseen `INFO` log messages:
`Peer reachability status                   topics="wakunode" tid=1 file=waku_node.nim:225 networkReachability=NotReachable confidence=1.0`

### Impact
I am uncertain of the impact; the node still appears to have ~2 dozen connected peers but the log suggests that the node is not reachable

### To reproduce
I'm unaware of any special steps or configurations required to reproduce. The node is running relay protocol only (no store, filter, etc) with rln disabled.

### Expected behavior
If the message does not actually mean that my node is unreachable, it should not cause alarm by being logged as `INFO`

### Screenshots/logs
see attached

### nwaku version/commit hash
`version / git commit hash: v0.14.0`
[log.txt](https://github.com/waku-org/nwaku/files/10438065/log.txt)

**Comment by alrevuelta** [comment] 2023-01-18 07:59
> I am uncertain of the impact; the node still appears to have ~2 dozen connected peers but the log suggests that the node is not reachable

Are any of these connections inbound? A node can be `NotReachable` and still have connected peers (outbound peers).

Note though that this is an experimental feature that was just released both in our side and nim-libp2p, and works by asking other peers if they can connect to you.

Does your node/computer have the waku port open? Or even if its closed do you have a router supporting upnp?

If you do expect your node to be reachable, and you want to give it a shot, feel free to experiment with the [autonatservice](https://github.com/waku-org/nwaku/blob/982cd28265cf0e17e07566aa096f68d733e9217b/waku/v2/node/waku_node.nim#L214-L221). Would suggest to enable `askNewConnectedPeers` and changing `numPeersToAsk` or `maxQueueSize`.

**Comment by alrevuelta** [comment] 2023-01-19 10:30
@dao After some discussions with nim-libp2p team, this is a known issue on `nim-libp2p`. This feature works by requesting other nodes to dial you, and if they succeed, they flag you as `Reachable` otherwise `NotReachable`.

Problem is that we currently limit the maximum number of connection a node can have to **1**. So if you are already connected the the peer that you are requesting to dial you to test your reachability, it will fail because you will reject that connection. This should explain why you see `NotReachable`.

We can also see that this metric is really unstable in our fleets, jumping quite often from `NotReachable` to `Reachable`.

By now you can ignore the logs. Thanks for reporting!

**Comment by alrevuelta** [comment] 2023-01-23 17:04
Work is being done in https://github.com/status-im/nim-libp2p/pull/845 and https://github.com/status-im/nim-libp2p/pull/846. Once fixed in `nim-libp2p` we will bump the version and should be fixed.

**Comment by alrevuelta** [comment] 2023-01-30 15:52
Just merged the nim-libp2p version bump containing the fixes. Will monitor our fleets (where the issue is also present) over the next 24 hours and check if the issue is resolved.

**Comment by alrevuelta** [comment] 2023-01-31 07:48
Can verify in our `wakuv2.test` fleets that the nim-libp2p version bump to `67939b` was deployed, containing `4ace70d53b0b0e3b58cd3bead70b967d34bd03f3` nim-libp2p version. However, I still see the issue: Reachable and NotReachable statuses are i) wrongly reported and ii) unstable.

<img width="1635" alt="image" src="https://user-images.githubusercontent.com/8811422/215698282-474f1786-e2d5-4b0d-8981-b5272b2f54a3.png">

This needs further investigation.

**Comment by alrevuelta** [comment] 2023-02-20 13:59
<img width="693" alt="image" src="https://user-images.githubusercontent.com/8811422/220126690-56190b37-7e4f-4fef-89d4-0261c72566d0.png">

An update on this. Latest nim-libp2p version included a fix but still a bit unstable. NotReachable state is still reported on nodes that are Reachable from time to time. Issue seems to happen more often when multiple nodes try to dial each other testing reachability at the same time.

This new issue was detected by nim-libp2p team and a fix should be ready soon. Once fixed, this should be closed once we bump to the latest version.

**Comment by alrevuelta** [comment] 2023-04-05 08:46
v0.16.0 should fix this.

I can verify it works in a private network with latest master. Will wait until we deploy this release to our fleets before closing.

**Comment by alrevuelta** [comment] 2023-05-30 09:50
v0.16.0 indeed fixed this, but if other nodes did not update, they may flag us as notreachable while being reachable. Since multiple nodes are queried for our state, its just matter of consensus (if more nodes report us as reachable then we will flag ourselves are reachable).

closing since this is fixed from v0.16.0

**Closed by alrevuelta** 2023-05-30 09:50 UTC
Labels: bug, track:maintenance
