### ISSUE TITLE
database migration requires too much storage

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#2727] opened 2024-05-23 19:46 UTC
### Problem
Step2 of the migration process does an INSERT SELECT. This approach is not ideal in scenarios in which a large number of messages are stored, since the storage requirements of running this migration might end up causing it to fail and be executed partially.
https://github.com/waku-org/nwaku/blob/cbaefeb3ea7059d1ab7aa44123f0030db90750e3/migrations/message_store_postgres/content_script_version_2.nim#L46-L64

### Suggested solution
Instead of doing an INSERT SELECT, consider setting the old messages table as a partition itself, as described in
https://rodoq.medium.com/partition-an-existing-table-on-postgresql-480b84582e8d 
Since the message retention policy is set to 30d, it should be possible to get rid of this partition manually later.

cc: @jakubgs

**Comment by jakubgs** [comment] 2024-06-14 08:04
This is a good idea, and would save us a lot of trouble in the future.

**Comment by SionoiS** [comment] 2024-07-02 13:24
I've looked into this and I don't know if it's possible. The problem is that the `messages` table is just a ref to the underlining partitions. To update "in-place", one would have to update each partition one by one. This can be done but in our case the name of these partitions are based on the local node timestamps and that we can't know in advance. So what do?

**Comment by Ivansete-status** [comment] 2024-07-17 16:52
Closing as we managed to apply that suggestion when we started to use partitions.
Thanks! :raised_hands:

**Closed by Ivansete-status** 2024-07-17 16:52 UTC
Labels: effort/days
